"""Initial migration for flights table

Revision ID: 38149a8d2f1b
Revises: 
Create Date: 2024-10-24 12:30:05.557087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38149a8d2f1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airport_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flight_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flight_time', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('retrieved_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flights_pkey')
    )
    # ### end Alembic commands ###
