version: "3.9"
services:
    database:
        container_name: "postgres"
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=dhmi-scrape"
        volumes:
            - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:

